apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: trigger-jenkins-pipelinerun
spec:
  pipelineRef:
    name: trigger-jenkins-pipeline
  params:
    - name: JENKINS_HOST_URL
      value: $(params.JENKINS_HOST_URL)
    - name: JOB_NAME
      value: $(params.JOB_NAME)
    - name: JENKINS_SECRETS
      value: $(params.JENKINS_SECRETS)
    - name: JOB_PARAMS
      value: ["$(params.JOB_PARAMS[*])"]
  workspaces:
    - name: source
      emptyDir: {}